name: upload-service
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout/@v2
      - name: action/setup-node
        run: chmod +x ./deploy.sh && ./deploy.sh
        shell: bash
      - name: action/login-hub
        uses: docker/login-action@v1
        with:
          username: abeesdevjs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: action/setup-buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: action/docker-buildx-action
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./deploy
          file: ./deploy/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: 'abeesdevjs/upload-service:${{  github.ref_name }}'
